param(
    [Parameter(Mandatory=$true)][string]$KeyPath,
    [Parameter(Mandatory=$true)][string]$OutCs
)

$bytes = [System.IO.File]::ReadAllBytes($KeyPath)
if ($bytes.Length -ne 32) {
    Write-Error "Key file is $($bytes.Length) bytes, expected 32."
    exit 1
}
$literal = ($bytes | ForEach-Object { "0x{0:x2}" -f $_ }) -join ', '

$template = @'
using System;
using System.Diagnostics;
using System.Security.Cryptography;
using System.Text;

// Auto-generated by assets\gen-token-source.ps1 from config\.profile_key.
// Mirrors chrome/browser/license/license_gate.cc's token scheme exactly:
// HMAC-SHA256(secret, "{ts}|{ppid}" + 16 random nonce bytes)[:16].
// This is a COMPILED binary specifically so the secret isn't sitting in
// a plaintext script anyone can open in Notepad -- see
// patches/REBASE-153.md for why chronium.ps1 can't safely do this itself.
class GenToken {
    static readonly byte[] Secret = { __SECRET_BYTES__ };

    static int Main(string[] args) {
        int ppid = Process.GetCurrentProcess().Id;
        for (int i = 0; i < args.Length; i++) {
            if (args[i] == "--ppid" && i + 1 < args.Length) {
                ppid = int.Parse(args[i + 1]);
            }
        }

        long ts = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        byte[] nonce = new byte[16];
        using (var rng = RandomNumberGenerator.Create()) {
            rng.GetBytes(nonce);
        }

        string prefix = ts + "|" + ppid;
        byte[] prefixBytes = Encoding.ASCII.GetBytes(prefix);
        byte[] msg = new byte[prefixBytes.Length + nonce.Length];
        Buffer.BlockCopy(prefixBytes, 0, msg, 0, prefixBytes.Length);
        Buffer.BlockCopy(nonce, 0, msg, prefixBytes.Length, nonce.Length);

        byte[] full;
        using (var h = new HMACSHA256(Secret)) {
            full = h.ComputeHash(msg);
        }
        byte[] token = new byte[16];
        Buffer.BlockCopy(full, 0, token, 0, 16);

        string nonceHex = BitConverter.ToString(nonce).Replace("-", "").ToLowerInvariant();
        string tokenHex = BitConverter.ToString(token).Replace("-", "").ToLowerInvariant();

        Console.WriteLine(
            "--license-ts=" + ts +
            " --license-nonce=" + nonceHex +
            " --license-token=" + tokenHex);
        return 0;
    }
}
'@

$content = $template -replace '__SECRET_BYTES__', $literal
Set-Content -Path $OutCs -Value $content -Encoding ascii
Write-Output "Wrote $OutCs"
